### ISSUE TITLE
Renaming files

### ISSUE THREAD

**Issue by tomomonta** [CharlieDigital/coderev#10]
Right now I can't rename files and I have to remake them to correct any naming. Would be great to be able to simply click and rename.

**Comment by CharlieDigital** [comment]
I'll try to get this in some time this week!

**Comment by CharlieDigital** [comment]
OK; got this shipped!  Give it a go!

See the PR for limitations.

https://github.com/CharlieDigital/coderev/assets/779970/5093fe37-750c-4878-8c33-3344928f743a
