### ISSUE TITLE
Disable persistent modal to allow escape key to be used to close dialogs

### ISSUE THREAD

**Issue by victorgdb** [CharlieDigital/coderev#2]
Thank you for this great project!

When I tried to use the escape key to close a dialog, it's not working. It's because of the `persistent` dialog option from Qasar.
If you are interested in changing this aspect, you might remove this property in `SideDialogShell.vue:8` 

Thanks again for your work

**Comment by CharlieDigital** [comment]
Good idea!

I've made the change and changed the shell to be non-persistent by default.

The one exception is the `PreferencesDialog` before the user has explicitly set a notification option.

Thanks for the feedback!
