### ISSUE TITLE
Suggestion: add a view of the reviews I'm doing or have done

### ISSUE THREAD

**Issue by Jeremyvp** [CharlieDigital/coderev#9]
The app looks promising, thanks!

During testing the reviewer wasn't able to see the review he is doing when closing and opening the site again. Only via the link the reviewer was originally given were they able to see their review again.

It would be nice if there was a dashboard/view that shows the current and past reviews so that the link doesn't need to be saved.

**Comment by CharlieDigital** [comment]
Thanks for the suggestion; I'll add this to my backlog.

**Comment by CharlieDigital** [comment]
This has shipped:

![image](https://github.com/CharlieDigital/coderev/assets/779970/d9f34536-adad-4edc-9742-8420bf02cfa4)

You can test this by assigning an alternate email as candidate to a test workspace.  The alternate email will see the "As Candidate" section in their view.

Please let me know if you run into issues or have other suggestions.
